version: 2
jobs:
  build:
    docker:
      - image: cr0hn/python3.6-alpine-make:1.0.4

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 17.07.0-ce

      - deploy:
          name: Upload to pypi
          command: make upload-pypi
          filters:
            tags:
              only: /.*/